# Generated by Django 2.2.4 on 2021-03-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
